### ISSUE TITLE
#1172 Relationships - Delete Rules

### ISSUE THREAD

**Issue by jaecSolutions** [jaecSolutions/unito-pods#96]
I've been working with Xcode lately on an iPad app project. While in the Data Model manager, I noticed something with how Xcode handles relationships and the deletion of their parent entity.

So let's say you have a Book with Chapters, and let's say you've created two content types - one for each respectively.

What Xcode data modeling allows for is a special 'delete rule' on the Author > Book > Chapter relationships. Here's a few scenarios:

* **Deny:** Delete an Author, but don't let me delete it if it has books
* **Cascade:** Delete an Author, and delete it's related books; If the books have related chapters and that relationship is marked as cascade, delete related chapters; Continue cascading
* **No Action:** Delete an Author, and do nothing

It has another option called 'Nullify' but it's functionally the same as no action in the Pods world.

Additionally, since we'll be using a UI in many operations, we should be able to add another scenario for:

* **Reassign:** Delete an Author, reassign the related books to another author

You're probably most familiar with how this works as it's the same UI when deleting a User. It takes you to an interim screen to choose what to do with their posts: Reassign / Delete All Posts.

## Task List

- [ ] **Add Delete Rules to Relationships options:** No Action (default), Cascade, Deny, Reassign
- [ ] **Cascade:** Pre-deletion of parent item, attempt to delete related items, then delete parent item
- [ ] **Cascade Recurse:** Check related item's relationship delete rules and follow them, then delete related item
- [ ] **Deny:** Pre-deletion of parent item, check if relationship delete rules match a 'deny' and stop/warn deletion; Otherwise, delete parent item
- [ ] **Cascade Recurse on Deny:** If related item's relationship delete rules match a 'deny', block deletion of parent item; Otherwise, delete parent item
- [ ] **Reassign:** Pre-deletion of parent item when using UI for deleting, provide interim screen with drop-down to reassign the relationship to another parent item, to delete all related items, or to leave alone (orphan the related items)
- [ ] **Reassign via API:** Allow parameter to be sent for relationship reassignment (relationship_field > new id), if no parameter present, delete relationships but not related items (backwards compatibility)
